# Generated by Django 3.0.4 on 2020-04-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contact',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='instagram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='smptemail',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='setting',
            name='smptpassword',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='setting',
            name='smptport',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='setting',
            name='smptpserver',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='setting',
            name='twitter',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
