# Generated by Django 3.0.4 on 2020-05-01 02:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200501_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contact_map',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
